language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-4.9
      - libcppunit-dev
      - libboost-system-dev
      - libgtest-dev

compiler:
  - g++

before_install:
  - pip install --user cpp-coveralls
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib
install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

script:
  - cmake .; make clean; make UnitTest
after_success:
  - coveralls -t tq50tWpv29zRsnWS81mqZx9oSpYca8LkI -i source/