sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-4.9
      - libcppunit-dev
      - libgtest-dev

compiler:
  - g++

before_install:
  - pip install --user cpp-coveralls
  - mkdir ~/gtest && cd ~/gtest && cmake /usr/src/gtest -DBUILD_SHARED_LIBS=ON && make && sudo cp -vp libgtest*.so /usr/local/lib/ && sudo ldconfig && cd -
install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

script:
  - cmake -DCOVERAGE:STRING=TRUE .; make clean; make UnitTest
after_success:
  - coveralls -t tq50tWpv29zRsnWS81mqZx9oSpYca8LkI -i source/ --gcov gcov-4.9