language: cpp

compiler:
  - g++

before_install:
  # g++4.9
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo add-apt-repository -y ppa:george-edison55/cmake-3.x; fi
  - sudo apt-get update -qq

install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9;  sudo apt-get install -qq libcppunit-dev; sudo apt-get install -qq libboost-system-dev; sudo apt-get install -qq cmake; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

script:
  - cmake .;make UnitTest